---
title: "Map Making"
author: "Lamar Foster"
date: "6/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = F, warning = F)
```

```{r}
library(tidyverse)
library(gganimate)
library(janitor)
library(RColorBrewer)
library(highcharter)
```

```{r}
# Read USDA ERS dataset
county_df <- read.csv("mapdata/People.csv") %>% filter(State == "WA")

# Load Washington county map
wa_counties <- get_data_from_map(download_map_data("countries/us/us-wa-all"))
```

```{r}
#Make a density variable 
density_df <- county_df %>%   
  select(c(fips=FIPS,County,TotalPopEst2018,LandAreaSQMiles2010)) %>%
  mutate(density = round(TotalPopEst2018/LandAreaSQMiles2010,0))
```

```{r}
# Make the map 
density_map <- hcmap(map = "countries/us/us-wa-all", 
      data = density_df, 
      value = "density", 
      joinBy = c("fips"),
      borderWidth = 0.3)  %>%
  hc_mapNavigation(enabled = TRUE) %>% 
  hc_legend(layout = "vertical", 
            align = "right",
            valueDecimals = 0) %>% 
  hc_colorAxis(dataClasses = color_classes(breaks = c(0,10,25,50,100,250,500,1000,2500,max(density_df$density)),
              colors = brewer.pal(name="Purples",n=9)))

```

```{r}
density_map <- density_map %>%
    hc_tooltip(formatter = JS("function() {
  return ('<br><b>County:</b> ' + this.point.County +
          '<br><b>Population Density:</b> ' + this.point.density + ' people per sq mi'
  )}"))
```

```{r}
# Calculate population density for each year in dataset
pop_density <- function(x){
  round(x/county_df$LandAreaSQMiles2010,0)
}

density_df_by_year <- county_df %>% 
  select(c(FIPS,State,County,
           '2010'=TotalPopEst2010,
           '2011'=TotalPopEst2011,
           '2012'=TotalPopEst2012,
           '2013'=TotalPopEst2013,
           '2014'=TotalPopEst2014,
           '2015'=TotalPopEst2015,
           '2016'=TotalPopEst2016,
           '2017'=TotalPopEst2017,
           '2018'=TotalPopEst2018)) %>%
  mutate_at(vars(matches("201")),pop_density) %>%
  filter(State == 'WA') %>%
  gather(year,density,-c(FIPS,State,County)) %>%
  mutate(fips = ifelse(nchar(FIPS)<5,paste0("0",FIPS),FIPS)) %>%
  filter(!grepl('000',FIPS),
         !State == 'US')
```

```{r}
# Create list column containing population densities by year 
density_df_seq <- density_df_by_year %>%
  group_by(fips) %>%
  do(sequence = list_parse(select(., value = density)))
```

```{r}
# Join with original dataset
density_df_by_year <- left_join(density_df_by_year,density_df_seq)
```

```{r}
animated_map <- hcmap(map = "countries/us/us-wa-all", 
      data = density_df_by_year, 
      value = "density", 
      joinBy = c("fips"),
      borderWidth = 0.3)  %>%
  hc_mapNavigation(enabled = TRUE) %>% 
   hc_colorAxis(dataClasses = color_classes(breaks = c(0,10,25,50,100,250,500,1000,2500,max(density_df_by_year$density)),
              colors = brewer.pal(name="Purples",n=9))) %>%
  hc_legend(layout = "vertical", 
            align = "right") %>% 
  hc_title(text = "Population Density by County, 2010 to 2018") %>%
  hc_credits(enabled = TRUE,
             text = "Author: James Lamar Foster, Data: USDA ERS",
             href = "https://www.ers.usda.gov/data-products/atlas-of-rural-and-small-town-america/download-the-data/")  
```


```{r}
animated_map <- hcmap(map = "countries/us/us-wa-all", 
      data = density_df_by_year, 
      value = "density", 
      joinBy = c("fips"),
      borderWidth = 0.3)  %>%
  hc_mapNavigation(enabled = TRUE) %>% 
   hc_colorAxis(dataClasses = color_classes(breaks = c(0,10,25,50,100,250,500,1000,2500,max(density_df_by_year$density)),
              colors = brewer.pal(name="Purples",n=9))) %>%
  hc_legend(layout = "vertical", 
            align = "right") %>% 
  hc_title(text = "") %>%
  hc_credits(enabled = TRUE,
             text = "Author: James Lamar Foster, Data: USDA ERS",
             href = "https://www.ers.usda.gov/data-products/atlas-of-rural-and-small-town-america/download-the-data/")  
```


```{r}
# Add animation to map
animated_map %>% 
      hc_motion(enabled = TRUE, 
          series = 0, 
          autoPlay = TRUE,
          loop = TRUE,
          labels = unique(density_df_by_year$year)) %>% 
  hc_motion(enabled = TRUE, 
          series = 0, 
          autoPlay = TRUE,
          loop = TRUE,
          labels = unique(density_df_by_year$year))

```


