---
title: "Another one...Map"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(gganimate)
library(rvest)
library(lubridate)
library(gifski)
library(ggrepel)
library(scales)
```

```{r}
link <- "https://lni.wa.gov/workers-rights/wages/minimum-wage/history-of-washington-states-minimum-wage"
page <- read_html(link)
Date <-  page %>% html_nodes("td:nth-child(1)") %>% html_text()
Wage <- page %>% html_nodes("td+ td") %>% html_text()
#Turn into data frame 
df_wage <- data.frame(Date, Wage)
```

```{r}
glimpse(df_wage)

#Quick Clean of data set 
wa_wage <- df_wage %>% 
  slice(-1) %>% 
  mutate(Wage = parse_number(Wage)) %>% 
  mutate(Date = mdy(Date)) %>% 
  mutate(State = "WA")

#Separate Date column
wa_year <- wa_wage %>% 
mutate(Date = as.integer(format(wa_wage$Date, "%Y")))
```


```{r}
#Visualize WA min wage df 
w <- ggplot(wa_year, aes(Date, Wage)) + 
  geom_line(color = "#4b2e83") + 
  geom_point(aes(group =seq_along(Date)), color = "#85754d") + 
  scale_y_continuous(breaks = 0:15, labels= label_dollar()) + 
  theme_bw() +  
  labs(title = 'Washington State Minimum Wage', x = 'Year', y = 'Minimum Wage') +
  transition_reveal(Date) 

animate(w, renderer = gifski_renderer())

anim_save("wa_minwage.gif", w)

```

